server {
    listen 80;
    listen [::]:80;

    server_name k8s.vim0.com _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}
